FROM centos:7

RUN ACCEPT_EULA=Y \
  yum install -y sudo vim git wget build-essential lzma-devel curl perl-core perl-IPC-Cmd dialog apt-utils ca-certificates apt-transport-https locales gnupg2 openssl lsb-release

run curl https://packages.microsoft.com/config/rhel/7/prod.repo > /etc/yum.repos.d/mssql-release.repo

run yum remove unixODBC-utf16 unixODBC-utf16-devel

run yum install -y unixODBC-devel

RUN ACCEPT_EULA=Y \
  yum install -y python3 unixodbc unixodbc-dev unixODBC-devel libiodbc

RUN ACCEPT_EULA=Y \
  yum install -y msodbcsql18
RUN ACCEPT_EULA=Y \
  yum install -y mssql-tools18

run curl -sL https://rpm.nodesource.com/setup_16.x | bash -
RUN ACCEPT_EULA=Y \
  yum install -y nodejs iputils
RUN npm install --g yarn
RUN npm install --g yarn
RUN npm install --g npm-check-updates
RUN useradd -ms /bin/bash apprunner
USER apprunner
RUN mkdir -p ~/miniconda3
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh
RUN bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3
RUN rm -rf ~/miniconda3/miniconda.sh
RUN ~/miniconda3/bin/conda init bash

RUN (export PATH="$HOME/miniconda3/bin:$PATH"; conda create --name msodbc; conda activate msodbc; conda install -c anaconda gcc_linux-64=11.2.0 gxx_linux-64=11.2.0)

USER root
# RUN (cd /usr/lib64; mv libstdc++.so.6 libstdc++.so.6.orig; cp /home/apprunner/miniconda3/lib/libstdc++.so libstdc++.so.29; ln -s libstdc++.so.29 libstdc++.so.6)
USER apprunner
RUN mkdir -p $HOME/projects
RUN git clone https://github.com/openssl/openssl.git --depth 1 --branch openssl-3.1.1 $HOME/projects/openssl
RUN (export PATH="$HOME/miniconda3/bin:$PATH"; conda activate msodbc; export CC=x86_64-conda_cos7-linux-gnu-cc; cd $HOME/projects/openssl ; ./config --prefix=/usr/local/ssl --openssldir=/usr/local/ssl shared; make; )
USER root
RUN (cd /home/apprunner/projects/openssl; make install)
RUN (cd /etc/ld.so.conf.d/; echo '/usr/local/ssl/lib64/' | tee openssl-3.2.0.1s.conf;)
RUN (cd /usr/local/ssl; mv certs certs.old; ln -s /etc/ssl/certs certs)
RUN ldconfig -v
run yum group install -y "Development Tools"
USER apprunner
RUN (export PATH="$HOME/miniconda3/bin:$PATH"; conda activate msodbc; mkdir -p $HOME/app; cd $HOME/app; git clone https://github.com/TimelordUK/msnodesqlv8_yarn_sample.git; cd msnodesqlv8_yarn_sample);
RUN (mkdir -p $HOME/app; cd $HOME/app; git clone https://github.com/TimelordUK/msnodesqlv8_yarn_sample.git; cd msnodesqlv8_yarn_sample;)
RUN (mkdir -p $HOME/app/driver/node_modules; cd $HOME/app/driver/node_modules; odbcinst -j; git clone https://github.com/TimelordUK/node-sqlserver-v8.git msnodesqlv8; cd msnodesqlv8; )
